export const frMenuPage = {
  eyebrow: 'Le menu',
  title: 'La carte de La Table',
  text:
    'Une lecture plus simple de la carte, pensée pour distinguer tout de suite la cuisine, les pizzas, le bar, les vins, les softs, les cafés et les desserts.',
  note: 'Validation en français uniquement pour cette passe.',
  tabs: [
    {
      id: 'cuisine',
      label: 'Cuisine',
      sections: [
        {
          id: 'sharing',
          title: 'À partager',
          desktopColumn: 0,
          items: [
            { name: 'Caviar d’aubergines au feu de bois', price: '8 €' },
            { name: 'Poivrons marinés, pain à pizza', price: '8 €' },
            { name: 'Panisses, sauce aïoli', price: '9 €' },
            { name: 'Jambon de Parme', price: '11 €' },
            { name: 'Socca du chef « Yann »', price: '7 €' },
          ],
        },
        {
          id: 'starters',
          title: 'Entrées',
          desktopColumn: 0,
          items: [
            { name: 'Burrata, tomates anciennes', price: '19 €' },
            { name: 'César de volaille panée', price: '18 €' },
            { name: 'Artichaut en salade', price: '17 €' },
            { name: 'Sériole en ceviche', price: '18 €' },
            { name: 'Thon snacké, façon salade « niçoise »', price: '20 €' },
            { name: 'Quinoa et ses condiments du jour', price: '19 €' },
          ],
        },
        {
          id: 'mains',
          title: 'Plats',
          desktopColumn: 1,
          items: [
            { name: 'Travers de porc marinés', price: '23 €' },
            { name: 'Tagliata de bœuf', price: '25 €' },
            { name: 'Bœuf en tartare à l’italienne', price: '19 €' },
            { name: 'Burger gourmand à la crème de cheddar', price: '19 €' },
            { name: 'Joue de bœuf confite', price: '23 €' },
            { name: 'Suprême de volaille rôtie, sauce aux cèpes', price: '25 €' },
            { name: 'Linguini au pesto', price: '20 €' },
            { name: 'Veau, en escalope milanaise', price: '26 €' },
            { name: 'Rigatoni à l’arrabbiata et stracciatella', price: '23 €' },
            { name: 'Linguini aux vongoles', price: '25 €' },
            { name: 'Rigatoni à la crème de truffes', price: '32 €' },
            { name: 'Moules marinières', price: '18 €' },
            { name: 'Sardines grillées, vierge de saison', price: '19 €' },
            { name: 'Gambas sauvages poêlées à l’ail', price: '28 €' },
            { name: 'Daurade royale entière rôtie au four', price: '32 €' },
          ],
        },
        {
          id: 'extras',
          title: 'Garnitures',
          desktopColumn: 0,
          items: [
            { name: 'Frites fraîches', price: '5 €' },
            { name: 'Polenta crémeuse', price: '5 €' },
            { name: 'Mesclun niçois', price: '5 €' },
            { name: 'Légumes du soleil', price: '5 €' },
          ],
        },
        {
          id: 'kids',
          title: 'Menu enfant',
          desktopColumn: 1,
          items: [
            {
              name: 'Menu enfant',
              description: 'Sirop à l’eau, tenders frites ou pâtes à la sauce tomate, boule de glace',
              price: '12 €',
            },
          ],
        },
      ],
    },
    {
      id: 'pizzas',
      label: 'Pizzas',
      sections: [
        {
          id: 'wood-fired-pizzas',
          title: 'Pizzas au feu de bois',
          layout: 'split-items',
          items: [
            { name: 'Marguerite', description: 'Sauce tomate, mozzarella, basilic', price: '14 €' },
            { name: 'Reine', description: 'Sauce tomate, mozzarella, jambon cuit, champignons', price: '17 €' },
            {
              name: '4 fromages',
              description: 'Sauce tomate, mozzarella, reblochon, roquefort, chèvre',
              price: '17 €',
            },
            {
              name: 'Cannibale',
              description: 'Sauce tomate, mozzarella, oignons confits, viande hachée, œuf',
              price: '18 €',
            },
            { name: 'Napolitaine', description: 'Sauce tomate, mozzarella, anchois, câpres', price: '16 €' },
            {
              name: '4 saisons',
              description: 'Sauce tomate, mozzarella, champignons, aubergines, tomates cerises, artichauts',
              price: '18 €',
            },
            {
              name: 'Provençale',
              description: 'Sauce tomate, mozzarella, champignons, aubergines, oignons confits, poivrons',
              price: '18 €',
            },
            { name: 'Espagnole', description: 'Sauce tomate, mozzarella, spianata, poivrons', price: '18 €' },
            {
              name: 'Méditerranée',
              description: 'Sauce tomate, mozzarella, oignons confits, câpres, thon',
              price: '19 €',
            },
            {
              name: 'Parma',
              description: 'Sauce tomate, mozzarella, tomates cerises, jambon cru, burrata',
              price: '22 €',
            },
            {
              name: 'Norvégienne',
              description: 'Base blanche, mozzarella, saumon mariné, tomates cerises',
              price: '19 €',
            },
            { name: 'Chèvre-miel', description: 'Base blanche, mozzarella, chèvre, noix, miel', price: '17 €' },
            {
              name: 'Calzone',
              description: 'Sauce tomate, mozzarella, champignons, jambon cuit, œuf',
              price: '18 €',
            },
            { name: 'Truffala', description: 'Crème de truffe, mozzarella, jambon cru, burrata', price: '25 €' },
          ],
        },
      ],
    },
    {
      id: 'bar',
      label: 'Bar',
      sections: [
        {
          id: 'spritz',
          title: 'Spritz',
          desktopColumn: 0,
          items: [
            { name: 'Aperol Spritz', description: 'Apérol 5 cl, prosecco 10 cl, eau gazeuse, orange', price: '10 €' },
            { name: 'Hugo Spritz', description: 'St-Germain 5 cl, prosecco 10 cl, eau gazeuse, citron, menthe', price: '12 €' },
            { name: 'Limoncello Spritz', description: 'Limoncello 5 cl, prosecco 10 cl, eau gazeuse, citron', price: '10 €' },
            { name: 'Amaretto Spritz', description: 'Amaretto 5 cl, prosecco 10 cl, eau gazeuse, orange', price: '11 €' },
            { name: 'St-Germain Spritz', description: 'St-Germain 5 cl, prosecco 10 cl, eau gazeuse, citron', price: '12 €' },
            { name: 'Martini Spritz', description: 'Martini blanc 5 cl, prosecco 10 cl, eau gazeuse, citron', price: '10 €' },
            { name: 'Campari Spritz', description: 'Campari 5 cl, prosecco 10 cl, eau gazeuse, orange', price: '12 €' },
            {
              name: 'Spritz fruits rouges',
              description: 'Liqueur de fruits rouges 5 cl, prosecco 10 cl, eau gazeuse',
              price: '12 €',
            },
            { name: 'Rosa Spritz', description: 'Sarti 5 cl, prosecco 10 cl, eau gazeuse, orange', price: '11 €' },
            { name: 'Artichaut Spritz', description: 'Cynar 5 cl, prosecco 10 cl, eau gazeuse', price: '12 €' },
          ],
        },
        {
          id: 'cocktails',
          title: 'Cocktails',
          desktopColumn: 0,
          items: [
            { name: 'Negroni', description: 'Gin 3 cl, Campari 3 cl, vermouth rouge 3 cl', price: '12 €' },
            {
              name: 'Sex on the Beach',
              description: 'Vodka 5 cl, jus d’orange, jus de cranberry, liqueur de pêche',
              price: '12 €',
            },
            {
              name: 'Mojito fraise ou passion',
              description:
                'Rhum 5 cl, angostura, cassonade, citron vert, menthe, eau gazeuse, purée de fraise ou passion',
              price: '13 €',
            },
            {
              name: 'Mojito',
              description: 'Rhum 5 cl, angostura, cassonade, citron vert, menthe, eau gazeuse',
              price: '12 €',
            },
            { name: 'Sour', description: 'Amaretto, vodka, gin, rhum ou whisky 5 cl', price: '13 €' },
            {
              name: 'Pornstar',
              description: 'Vodka 5 cl, citron, vanille, jus de passion et prosecco 5 cl',
              price: '14 €',
            },
            { name: 'Pina Colada', description: 'Rhum 5 cl, lait de coco, jus d’ananas', price: '14 €' },
            {
              name: 'Daiquiri passion ou fraise',
              description: 'Rhum 5 cl, sucre de canne, citron vert, purée de passion ou de fraise',
              price: '14 €',
            },
            {
              name: 'Paloma',
              description: 'Tequila 5 cl, jus de citron vert, jus de pamplemousse, tonic',
              price: '13 €',
            },
            {
              name: 'Cosmopolitan',
              description: 'Vodka 5 cl, triple sec, jus de cranberry, citron vert',
              price: '13 €',
            },
            { name: 'Mule', description: 'Moscow, London, Mexican, Kentucky ou Caribbean 5 cl', price: '13 €' },
            {
              name: 'Grand Margarita',
              description: 'Grand Marnier 2 cl, tequila 3 cl, citron vert, sirop d’agave',
              price: '15 €',
            },
            {
              name: 'Expresso Martini',
              description: 'Vodka 5 cl, liqueur de café 2 cl, espresso, sirop de vanille',
              price: '15 €',
            },
          ],
        },
        {
          id: 'aperitifs',
          title: 'Apéritifs',
          desktopColumn: 1,
          items: [
            { name: 'Kir (14 cl)', price: '6 €' },
            { name: 'Kir Royal (14 cl)', price: '12 €' },
            { name: 'Martini, Campari, Porto (4 cl)', price: '5 €' },
            { name: 'Pastis, Ricard (4 cl)', price: '5 €' },
            { name: 'Prosecco (14 cl)', price: '6 €' },
            { name: 'Coupe de Champagne (14 cl)', price: '10 €' },
            { name: 'Piscine de Champagne (16 cl)', price: '12 €' },
          ],
        },
        {
          id: 'spirits',
          title: 'Alcools',
          desktopColumn: 1,
          items: [
            { kind: 'section', label: 'Whisky & bourbon (4 cl)' },
            { name: 'William Lawson’s', price: '8 €' },
            { name: 'Jack Daniel’s, Honey, Fire', price: '10 €' },
            { name: 'Chivas 12 ans', price: '13 €' },
            { name: 'Angels Envy', price: '15 €' },
            { name: 'Nikka From The Barrel', price: '22 €' },
            { kind: 'section', label: 'Vodka (4 cl)' },
            { name: 'Eristoff', price: '8 €' },
            { name: 'Grey Goose', price: '14 €' },
            { kind: 'section', label: 'Téquila (4 cl)' },
            { name: 'Acayucan', price: '8 €' },
            { name: 'Patron Silver', price: '15 €' },
            { kind: 'section', label: 'Gin (4 cl)' },
            { name: 'Bombay Original', price: '8 €' },
            { name: 'Bombay Sapphire', price: '12 €' },
            { name: 'Star of Bombay', price: '15 €' },
            { kind: 'section', label: 'Rhum (4 cl)' },
            { name: 'Bacardi Blanc', price: '8 €' },
            { name: 'Captain Morgan', price: '9 €' },
            { name: 'Diplomatico', price: '13 €' },
            { name: 'Santa Theresa', price: '16 €' },
            { kind: 'section', label: 'Digestifs (4 cl)' },
            { name: 'Get 27', price: '8 €' },
            { name: 'Get 31', price: '9 €' },
            { name: 'Limoncello', price: '8 €' },
            { name: 'Amaretto', price: '8 €' },
            { name: 'Sambuca', price: '8 €' },
            { name: 'Grappa', price: '9 €' },
            { name: 'Bailey’s', price: '9 €' },
            { name: 'Saint-Germain', price: '10 €' },
            { name: 'Armagnac Laubade', price: '12 €' },
            { name: 'Hennessy VS', price: '12 €' },
            { name: 'Hennessy XO', price: '28 €' },
            { name: 'Chartreuse Verte', price: '15 €' },
            { kind: 'section', label: 'Accompagnements' },
            { name: 'Soft', price: '+1 €' },
            { name: 'Red Bull', price: '+2,50 €' },
          ],
        },
      ],
    },
    {
      id: 'wines',
      label: 'Vins',
      sections: [
        {
          id: 'french-wines',
          title: 'Vins de France',
          desktopColumn: 0,
          items: [
            { kind: 'section', label: 'Vins rouges' },
            { name: 'Cellier des Chartreux | AOP Côtes du Rhône', price: 'Verre 6 €' },
            {
              name: 'Château Paradis Cuvée Essentiel | AOP Coteaux d’Aix-en-Provence',
              price: '50 cl 19 € • 75 cl 28 €',
            },
            { name: 'Pinot Noir Les Plans Nobles Ropiteau | Vin de France', price: '75 cl 30 €' },
            { name: 'Cuvée Perrin | AOP Côtes du Rhône', price: '75 cl 35 €' },
            { name: 'Les Domaniales | AOP Crozes-Hermitage', price: '75 cl 45 €' },
            { name: 'Famille Perrin Méridion | AOP Châteauneuf-du-Pape', price: '75 cl 76 €' },
            { name: 'Jean Claude Boisset | Hautes Côtes de Nuits AOP', price: '75 cl 72 €' },
            { name: 'La Colombière | AOP Saint-Émilion', price: '75 cl 47 €' },
            { name: 'Le Seuil de Mazeyres | AOP Pomerol', price: '75 cl 65 €' },
            { kind: 'section', label: 'Vins blancs' },
            { name: 'Côté Terre, Chardonnay | IGP Languedoc', price: 'Verre 6 €' },
            { name: 'Château Paradis | AOP Coteaux d’Aix', price: '50 cl 19 € • 75 cl 28 €' },
            { name: 'Minuty Prestige | AOP Côtes de Provence', price: '75 cl 45 €' },
            { name: 'Domaine Tariquet « Premières Grives » | IGP Côtes de Gascogne', price: '75 cl 30 €' },
            { name: 'Chardonnay Les Plans Nobles Ropiteau | Vin de France', price: '75 cl 29 €' },
            { name: 'Domaine St Romble Paul Vattan | AOP Sancerre', price: '75 cl 49 €' },
            { name: 'Domaine de Maltaverne | AOP Pouilly-Fumé', price: '75 cl 44 €' },
            { name: 'Domaine Les Héritières | AOP Chablis', price: '75 cl 89 €' },
            { kind: 'section', label: 'Vins rosés' },
            { name: 'Côté Mer | IGP Méditerranée', price: 'Verre 5 €' },
            { name: 'Château Paradis Cuvée Essentiel | AOP Coteaux d’Aix', price: '50 cl 19 € • 75 cl 28 €' },
            { name: 'Château Maïme « Heritage » | AOP Côtes de Provence', price: '75 cl 36 €' },
            { name: 'Tasquier | AOP Côtes de Provence', price: '75 cl 32 €' },
            { name: 'Miraval | AOP Côtes de Provence', price: '75 cl 55 €' },
            { name: 'Minuty Prestige | AOP Côtes de Provence', price: '75 cl 59 €' },
          ],
        },
        {
          id: 'world-wines',
          title: 'Vins du monde',
          desktopColumn: 1,
          items: [
            { kind: 'section', label: 'Rouges — Italie' },
            { name: 'Nero D’Avola Lumà | DOP Sicilia', price: '75 cl 35 €' },
            { name: 'Lambrusco Amabile | I.G.T. Lella', price: '75 cl 28 €' },
            { kind: 'section', label: 'Blancs — Italie' },
            { name: 'Santa Margherita, Pinot Grigio | Valdadige DOC', price: '75 cl 33 €' },
            { name: 'Etna Bianco DOC | Azienda Tornatore', price: '75 cl 45 €' },
            { kind: 'section', label: 'Rouges — Espagne' },
            { name: 'Riscal 1860 | Castilla y Leon AOC', price: '75 cl 32 €' },
            { kind: 'section', label: 'Blancs — Nouvelle-Zélande' },
            { name: 'Fusional Sauvignon Blanc | Marlborough', price: '75 cl 35 €' },
            { kind: 'section', label: 'Rouges — Argentine' },
            { name: 'Clos de los Siete | Valle de Uco – Mendoza', price: '75 cl 39 €' },
            { kind: 'section', label: 'Rouges — États-Unis' },
            { name: 'Buena Vista La Petite Syrah | Vin de Californie', price: '75 cl 38 €' },
            { kind: 'section', label: 'Rouges — Chili' },
            { name: 'Mapu | Valle del Maule', price: '75 cl 30 €' },
          ],
        },
        {
          id: 'premium-cellar',
          title: 'Cave premium',
          desktopColumn: 1,
          items: [
            { kind: 'section', label: 'Vins blancs' },
            { name: 'Louis Cheze « Pagus Luminis » | Condrieu AOP', price: '75 cl 85 €' },
            { name: 'Comte Lafond « Grande Cuvée » | Sancerre AOC', price: '75 cl 89 €' },
            { name: 'Pernand-Vergelesses | AOC, Jadot', price: '75 cl 94 €' },
            { name: 'Château Simone | AOC', price: '75 cl 99 €' },
            { name: 'Chassagne-Montrachet AOP | Guy Amiot et Fils', price: '75 cl 110 €' },
            { name: 'Meursault AOC | Albert Grivault', price: '75 cl 135 €' },
            { kind: 'section', label: 'Vins rouges' },
            { name: 'Château Carbonnieux', price: '75 cl 85 €' },
            { name: 'Château de Pez | Saint-Estèphe AOC', price: '75 cl 94 €' },
            { name: 'Château Prieuré-Lichine | Margaux AOC', price: '75 cl 110 €' },
            { name: 'Côte-Rôtie AOP | Domaine du Monteillet « Fortis »', price: '75 cl 140 €' },
            { name: 'Nuits-Saint-Georges AOC | Domaine Faiveley « Montroziers »', price: '75 cl 145 €' },
            { name: 'Vosne-Romanée AOC | Domaine Faiveley', price: '75 cl 155 €' },
            { name: 'Château de Beaucastel | Châteauneuf-du-Pape AOC', price: '75 cl 165 €' },
          ],
        },
        {
          id: 'champagnes',
          title: 'Champagnes & bulles',
          desktopColumn: 0,
          items: [
            { name: 'Prosecco | Sensi', price: 'Verre 6 € • 75 cl 35 €' },
            { name: 'Henri Loriot | Champagne', price: 'Verre 12 € • 75 cl 70 €' },
            { name: 'Billecart-Salmon Brut Rosé', price: '75 cl 90 €' },
            { name: 'Billecart-Salmon Brut Réserve', price: '75 cl 120 €' },
            { name: 'Ruinart Blanc de Blancs', price: '75 cl 110 €' },
            { name: 'Ruinart Brut', price: '75 cl 150 €' },
            { name: 'Dom Pérignon Brut Vintage', price: '75 cl 300 €' },
          ],
        },
      ],
    },
    {
      id: 'softs',
      label: 'Softs',
      sections: [
        {
          id: 'cold-drinks',
          title: 'Boissons fraîches',
          items: [
            { name: 'Vittel et San Pellegrino 50 cl', price: '4 €' },
            { name: 'Vittel et San Pellegrino 100 cl', price: '7 €' },
            { name: 'Sirop à l’eau', price: '3 €' },
            {
              name: 'Coca, Coca Zéro, Schweppes Tonic & Agrumes, Fuze Tea, Sprite, Perrier, Orangina (33 cl)',
              price: '5 €',
            },
            { name: 'Red Bull (25 cl)', price: '6 €' },
            {
              name: 'Jus de fruits (ACE, orange, tomate, pomme, ananas – 25 cl)',
              price: '5 €',
            },
            { name: 'Thé glacé pêche ou framboise', price: '6 €' },
            { name: 'Jus de fruits pressés (orange, citron – 25 cl)', price: '6 €' },
          ],
        },
        {
          id: 'mocktails',
          title: 'Mocktails',
          items: [
            { name: 'Virgin Spritz', price: '9 €' },
            { name: 'Virgin Mojito', price: '9 €' },
            { name: 'Virgin Colada', price: '9 €' },
            { name: 'Virgin Paloma', price: '9 €' },
            { name: 'Virgin Pornstar', price: '9 €' },
            { name: 'Virgin Exotique', price: '9 €' },
            { name: 'Virgin Sex On The Beach', price: '9 €' },
          ],
        },
      ],
    },
    {
      id: 'coffee',
      label: 'Cafés',
      sections: [
        {
          id: 'iced-coffee',
          title: 'Cafés glacés',
          desktopColumn: 1,
          items: [
            { name: 'Iced Latte', price: '4,50 €' },
            { name: 'Iced Caramel Latte', price: '5 €' },
            { name: 'Café frappé', price: '5 €' },
            { name: 'Iced Matcha Latte', price: '5,50 €' },
          ],
        },
        {
          id: 'hot-drinks',
          title: 'Boissons chaudes',
          layout: 'split-items',
          desktopColumn: 0,
          items: [
            { name: 'Café expresso', price: '2 €' },
            { name: 'Décaféiné', price: '2 €' },
            { name: 'Café noisette', price: '2,50 €' },
            { name: 'Café américain', price: '2,50 €' },
            { name: 'Cappuccino', price: '3,80 €' },
            { name: 'Café crème', price: '3,50 €' },
            { name: 'Double café', price: '4 €' },
            { name: 'Café viennois', price: '4,50 €' },
            { name: 'Thé, infusion', price: '4 €' },
            { name: 'Latte macchiato', price: '5 €' },
            { name: 'Irish coffee', price: '12 €' },
            { name: 'Chocolat chaud', price: '4 €' },
            { name: 'Chocolat viennois', price: '5 €' },
            { name: 'Latte vanille', price: '5 €' },
            { name: 'Latte caramel', price: '5 €' },
            { name: 'Latte noisette', price: '5 €' },
            { name: 'Chai Latte', price: '5 €' },
            { name: 'Matcha Latte', price: '5,50 €' },
          ],
        },
        {
          id: 'hot-drink-addons',
          title: 'Suppléments',
          desktopColumn: 1,
          items: [
            { name: 'Lait végétal', description: 'Avoine', price: '+0,90 €' },
            { name: 'Sirop', description: 'Vanille, caramel ou noisette', price: '+0,50 €' },
            { name: 'Chantilly', price: '+0,50 €' },
          ],
        },
      ],
    },
    {
      id: 'desserts',
      label: 'Desserts',
      sections: [
        {
          id: 'dessert-menu',
          title: 'Desserts',
          items: [
            { name: 'Assiette de fromages', price: '9 €' },
            { name: 'Mousse au chocolat', price: '8 €' },
            { name: 'Tiramisu du jour', price: '8 €' },
            { name: 'Paris-Antibes', price: '11 €' },
            { name: 'Tropézienne', price: '11 €' },
            { name: 'Tarte aux fruits de saison', price: '12 €' },
            { name: 'Pâtisserie du jour', price: '11 €' },
          ],
        },
        {
          id: 'ice-cream',
          title: 'Glaces',
          items: [
            {
              kind: 'section',
              label: 'Glaces artisanales',
            },
            {
              name: 'Parfums',
              description:
                'Café, chocolat, vanille, menthe, noix de coco, citron, fraise, mangue, passion, framboise, caramel, fleur de lait, ananas, pistache, bananerella, basilic',
            },
            { name: '1 boule', price: '3 €' },
            { name: '2 boules', price: '5,50 €' },
            { name: '3 boules', price: '7,50 €' },
            { kind: 'section', label: 'Coupes glacées' },
            { name: 'Dame Blanche', description: 'Glace vanille, sauce chocolat, chantilly', price: '9,50 €' },
            {
              name: 'Café ou chocolat liégeois',
              description: 'Glace vanille, glace café ou chocolat, café ou chocolat chaud, chantilly',
              price: '10 €',
            },
            { name: 'Coupe exotique', description: 'Glace noix de coco, mangue, passion, chantilly', price: '10,50 €' },
            {
              name: 'Coupe fruits rouges',
              description: 'Glace fraise et framboise, coulis de fruits rouges, chantilly',
              price: '11 €',
            },
            { name: 'Coupe Colonel', description: 'Glace citron, vodka, chantilly', price: '11 €' },
            {
              name: 'Coupe After Eight',
              description: 'Glace chocolat, menthe, Get 27, chocolat, chantilly',
              price: '11 €',
            },
            {
              name: 'Milk shake',
              description:
                'Glace + lait (33 cl) : framboise, ananas, fraise, banane, chocolat, vanille, mangue, passion, coco, citron',
              price: '7 €',
            },
          ],
        },
      ],
    },
  ],
};
