export const v5PagePlaceholderContent = {
  fr: {
    menu: {
      eyebrow: 'Le menu',
      title: 'Texte qui introduit la carte et explique qu’elle doit rester simple à mettre à jour',
      text: 'Court texte pour présenter le menu, la logique des catégories et le ton général de la cuisine.',
      note: 'Instruction client : remplacer chaque catégorie, chaque plat, chaque description et chaque prix par les contenus définitifs.',
      itemName: 'Nom du plat',
      itemDescription: 'Courte description du plat, de ses ingrédients principaux ou de son accompagnement.',
      itemPrice: 'Prix',
    },
    gallery: {
      eyebrow: 'Galerie',
      title: 'Texte qui explique les types de photos à fournir pour montrer le lieu',
      text: 'Court texte pour indiquer que cette page sert à montrer la terrasse, la salle, le bar, le four à bois, les assiettes et les détails du restaurant.',
      captions: [
        'Photo terrasse large',
        'Photo salle principale',
        'Photo four à bois',
        'Photo assiette signature',
        'Photo table dressée',
        'Photo bar bistrot',
      ],
    },
    about: {
      eyebrow: 'À propos',
      title: 'Texte qui pose l’identité du restaurant en quelques lignes',
      text: 'Court texte pour expliquer l’esprit du lieu, le quartier, l’ambiance, et ce qui distingue le restaurant.',
      frame: {
        eyebrow: 'Le cadre',
        title: 'Texte qui décrit le cadre, le quartier et les matières du lieu',
        text: 'Court texte pour présenter le Vieil Antibes, la terrasse, la salle, le bar, les pierres, le bois et les éléments visuels forts du restaurant.',
      },
      promise: {
        eyebrow: 'La promesse',
        title: 'Texte qui résume la promesse du restaurant et l’expérience attendue',
        text: 'Court texte pour expliquer le type de cuisine, le rythme midi et soir, le style de service et ce que le client vient chercher en venant ici.',
      },
      highlights: [
        'Argument court sur la terrasse',
        'Argument court sur le bar',
        'Argument court sur le four à bois',
        'Argument court sur les matières du lieu',
      ],
    },
    contact: {
      eyebrow: 'Contact',
      title: 'Texte qui rassure sur la réservation, l’adresse et les informations pratiques',
      text: 'Court texte pour expliquer comment réserver, comment venir et où trouver rapidement les informations utiles.',
      cards: [
        { title: 'Réservation téléphone', value: 'Numéro principal pour les réservations' },
        { title: 'WhatsApp', value: 'Lien ou numéro pour message direct' },
        { title: 'Email', value: 'Adresse email principale du restaurant' },
      ],
      addressTitle: 'Adresse',
      addressValue: 'Adresse complète du restaurant',
      hoursTitle: 'Horaires',
      hourValue: 'Horaires du jour à renseigner',
      accessTitle: 'Accès',
      accessText: 'Court texte avec les repères utiles, le stationnement si besoin et la meilleure façon de rejoindre le restaurant.',
    },
    legal: {
      eyebrow: 'Mentions légales',
      title: 'Texte qui introduit les informations administratives à fournir avant mise en ligne',
      text: 'Court texte pour indiquer que les informations légales finales seront remplacées avant la publication du site.',
      sections: [
        { title: 'Éditeur du site', body: 'Nom de la société, forme juridique, adresse, SIRET et représentant légal.' },
        { title: 'Hébergement', body: 'Nom de l’hébergeur, adresse, contact et informations techniques utiles.' },
        { title: 'Données personnelles', body: 'Texte légal final sur les données, le formulaire de contact si besoin, et la politique de confidentialité.' },
      ],
    },
  },
  en: {
    menu: {
      eyebrow: 'Menu',
      title: 'Text that introduces the menu and explains that it should stay easy to update',
      text: 'Short text introducing the menu, the category logic, and the general tone of the cuisine.',
      note: 'Client instruction: replace each category, dish, description, and price with the final real content.',
      itemName: 'Dish name',
      itemDescription: 'Short description of the dish, its main ingredients, or its garnish.',
      itemPrice: 'Price',
    },
    gallery: {
      eyebrow: 'Gallery',
      title: 'Text that explains which types of photos should be provided to show the place',
      text: 'Short text explaining that this page is meant to show the terrace, dining room, bar, wood oven, dishes, and restaurant details.',
      captions: [
        'Wide terrace photo',
        'Main dining room photo',
        'Wood oven photo',
        'Signature dish photo',
        'Set table photo',
        'Bistro bar photo',
      ],
    },
    about: {
      eyebrow: 'About',
      title: 'Text that defines the identity of the restaurant in a few lines',
      text: 'Short text explaining the spirit of the place, the area, the atmosphere, and what makes the restaurant distinct.',
      frame: {
        eyebrow: 'Setting',
        title: 'Text that describes the setting, the neighborhood, and the materials of the place',
        text: 'Short text introducing Vieil Antibes, the terrace, the dining room, the bar, the stone, the wood, and the strongest visual elements of the restaurant.',
      },
      promise: {
        eyebrow: 'Promise',
        title: 'Text that sums up the restaurant promise and the expected experience',
        text: 'Short text explaining the cuisine, lunch-to-dinner rhythm, service style, and what guests should come here for.',
      },
      highlights: [
        'Short point about the terrace',
        'Short point about the bar',
        'Short point about the wood oven',
        'Short point about the materials',
      ],
    },
    contact: {
      eyebrow: 'Contact',
      title: 'Text that reassures people about booking, address, and practical information',
      text: 'Short text explaining how to book, how to get there, and where to find practical information quickly.',
      cards: [
        { title: 'Phone booking', value: 'Main phone number for reservations' },
        { title: 'WhatsApp', value: 'Direct message link or number' },
        { title: 'Email', value: 'Main restaurant email address' },
      ],
      addressTitle: 'Address',
      addressValue: 'Full restaurant address',
      hoursTitle: 'Hours',
      hourValue: 'Day schedule to be filled in',
      accessTitle: 'Access',
      accessText: 'Short text with useful landmarks, nearby parking if relevant, and the easiest way to reach the restaurant.',
    },
    legal: {
      eyebrow: 'Legal notice',
      title: 'Text that introduces the legal information to provide before launch',
      text: 'Short text indicating that the final legal information will replace these placeholders before the site goes live.',
      sections: [
        { title: 'Website publisher', body: 'Company name, legal form, address, company number, and legal representative.' },
        { title: 'Hosting', body: 'Hosting provider name, address, contact details, and useful technical information.' },
        { title: 'Personal data', body: 'Final legal text about data handling, contact form usage if any, and privacy policy.' },
      ],
    },
  },
  it: {
    menu: {
      eyebrow: 'Menu',
      title: 'Testo che introduce il menu e spiega che deve restare facile da aggiornare',
      text: 'Breve testo per presentare il menu, la logica delle categorie e il tono generale della cucina.',
      note: 'Istruzione cliente: sostituire ogni categoria, ogni piatto, ogni descrizione e ogni prezzo con i contenuti definitivi.',
      itemName: 'Nome del piatto',
      itemDescription: 'Breve descrizione del piatto, dei suoi ingredienti principali o del contorno.',
      itemPrice: 'Prezzo',
    },
    gallery: {
      eyebrow: 'Galleria',
      title: 'Testo che spiega quali tipi di foto fornire per mostrare il locale',
      text: 'Breve testo per indicare che questa pagina serve a mostrare la terrazza, la sala, il bar, il forno a legna, i piatti e i dettagli del ristorante.',
      captions: [
        'Foto ampia della terrazza',
        'Foto della sala principale',
        'Foto del forno a legna',
        'Foto del piatto signature',
        'Foto della tavola apparecchiata',
        'Foto del bar bistrot',
      ],
    },
    about: {
      eyebrow: 'Chi siamo',
      title: 'Testo che definisce l’identità del ristorante in poche righe',
      text: 'Breve testo per spiegare lo spirito del luogo, il quartiere, l’atmosfera e ciò che rende il ristorante diverso.',
      frame: {
        eyebrow: 'Il contesto',
        title: 'Testo che descrive il contesto, il quartiere e i materiali del luogo',
        text: 'Breve testo per presentare il Vieil Antibes, la terrazza, la sala, il bar, la pietra, il legno e gli elementi visivi forti del ristorante.',
      },
      promise: {
        eyebrow: 'La promessa',
        title: 'Testo che riassume la promessa del ristorante e l’esperienza attesa',
        text: 'Breve testo per spiegare il tipo di cucina, il ritmo pranzo e cena, lo stile di servizio e ciò che il cliente viene a cercare qui.',
      },
      highlights: [
        'Argomento breve sulla terrazza',
        'Argomento breve sul bar',
        'Argomento breve sul forno a legna',
        'Argomento breve sui materiali del luogo',
      ],
    },
    contact: {
      eyebrow: 'Contatti',
      title: 'Testo che rassicura sulla prenotazione, l’indirizzo e le informazioni pratiche',
      text: 'Breve testo per spiegare come prenotare, come arrivare e dove trovare rapidamente le informazioni utili.',
      cards: [
        { title: 'Prenotazione telefonica', value: 'Numero principale per le prenotazioni' },
        { title: 'WhatsApp', value: 'Link o numero per messaggio diretto' },
        { title: 'Email', value: 'Indirizzo email principale del ristorante' },
      ],
      addressTitle: 'Indirizzo',
      addressValue: 'Indirizzo completo del ristorante',
      hoursTitle: 'Orari',
      hourValue: 'Orari del giorno da indicare',
      accessTitle: 'Accesso',
      accessText: 'Breve testo con i punti di riferimento utili, il parcheggio se necessario e il modo più semplice per raggiungere il ristorante.',
    },
    legal: {
      eyebrow: 'Note legali',
      title: 'Testo che introduce le informazioni amministrative da fornire prima della messa online',
      text: 'Breve testo per indicare che le informazioni legali finali saranno sostituite prima della pubblicazione del sito.',
      sections: [
        { title: 'Editore del sito', body: 'Nome della società, forma giuridica, indirizzo, numero di registrazione e rappresentante legale.' },
        { title: 'Hosting', body: 'Nome dell’hosting provider, indirizzo, contatti e informazioni tecniche utili.' },
        { title: 'Dati personali', body: 'Testo legale finale sul trattamento dei dati, sull’eventuale modulo di contatto e sulla privacy policy.' },
      ],
    },
  },
};
