export const v5PagePlaceholderContent = {
  fr: {
    menu: {
      eyebrow: 'Le menu',
      title: 'Texte qui introduit la carte et explique qu’elle doit rester simple à mettre à jour',
      text: 'Court texte pour présenter le menu, la logique des catégories et le ton général de la cuisine.',
      note: 'Instruction client : remplacer chaque catégorie, chaque plat, chaque description et chaque prix par les contenus définitifs.',
      itemName: 'Nom du plat',
      itemDescription: 'Courte description du plat, de ses ingrédients principaux ou de son accompagnement.',
      itemPrice: 'Prix',
    },
    gallery: {
      eyebrow: 'Galerie',
      title: 'Texte qui explique les types de photos à fournir pour montrer le lieu',
      text: 'Court texte pour indiquer que cette page sert à montrer la terrasse, la salle, le bar, le four à bois, les assiettes et les détails du restaurant.',
      captions: [
        'Photo terrasse large',
        'Photo salle principale',
        'Photo four à bois',
        'Photo assiette signature',
        'Photo table dressée',
        'Photo bar bistrot',
      ],
    },
    about: {
      eyebrow: 'À propos',
      title: 'Texte qui pose l’identité du restaurant en quelques lignes',
      text: 'Court texte pour expliquer l’esprit du lieu, le quartier, l’ambiance, et ce qui distingue le restaurant.',
      frame: {
        eyebrow: 'Le cadre',
        title: 'Texte qui décrit le cadre, le quartier et les matières du lieu',
        text: 'Court texte pour présenter le Vieil Antibes, la terrasse, la salle, le bar, les pierres, le bois et les éléments visuels forts du restaurant.',
      },
      promise: {
        eyebrow: 'La promesse',
        title: 'Texte qui résume la promesse du restaurant et l’expérience attendue',
        text: 'Court texte pour expliquer le type de cuisine, le rythme midi et soir, le style de service et ce que le client vient chercher en venant ici.',
      },
      highlights: [
        'Argument court sur la terrasse',
        'Argument court sur le bar',
        'Argument court sur le four à bois',
        'Argument court sur les matières du lieu',
      ],
    },
    contact: {
      eyebrow: 'Contact',
      title: 'Texte qui rassure sur la réservation, l’adresse et les informations pratiques',
      text: 'Court texte pour expliquer comment réserver, comment venir et où trouver rapidement les informations utiles.',
      cards: [
        { title: 'Réservation téléphone', value: 'Numéro principal pour les réservations' },
        { title: 'WhatsApp', value: 'Lien ou numéro pour message direct' },
        { title: 'Email', value: 'Adresse email principale du restaurant' },
      ],
      addressTitle: 'Adresse',
      addressValue: 'Adresse complète du restaurant',
      hoursTitle: 'Horaires',
      hourValue: 'Horaires du jour à renseigner',
      accessTitle: 'Accès',
      accessText: 'Court texte avec les repères utiles, le stationnement si besoin et la meilleure façon de rejoindre le restaurant.',
    },
    legal: {
      eyebrow: 'Mentions légales',
      title: 'Texte qui introduit les informations administratives à fournir avant mise en ligne',
      text: 'Court texte pour indiquer que les informations légales finales seront remplacées avant la publication du site.',
      sections: [
        { title: 'Éditeur du site', body: 'Nom de la société, forme juridique, adresse, SIRET et représentant légal.' },
        { title: 'Hébergement', body: 'Nom de l’hébergeur, adresse, contact et informations techniques utiles.' },
        { title: 'Données personnelles', body: 'Texte légal final sur les données, le formulaire de contact si besoin, et la politique de confidentialité.' },
      ],
    },
  },
  en: {
    menu: {
      eyebrow: 'Menu',
      title: 'Text that introduces the menu and explains that it should stay easy to update',
      text: 'Short text introducing the menu, the category logic, and the general tone of the cuisine.',
      note: 'Client instruction: replace each category, dish, description, and price with the final real content.',
      itemName: 'Dish name',
      itemDescription: 'Short description of the dish, its main ingredients, or its garnish.',
      itemPrice: 'Price',
    },
    gallery: {
      eyebrow: 'Gallery',
      title: 'Text that explains which types of photos should be provided to show the place',
      text: 'Short text explaining that this page is meant to show the terrace, dining room, bar, wood oven, dishes, and restaurant details.',
      captions: [
        'Wide terrace photo',
        'Main dining room photo',
        'Wood oven photo',
        'Signature dish photo',
        'Set table photo',
        'Bistro bar photo',
      ],
    },
    about: {
      eyebrow: 'About',
      title: 'Text that defines the identity of the restaurant in a few lines',
      text: 'Short text explaining the spirit of the place, the area, the atmosphere, and what makes the restaurant distinct.',
      frame: {
        eyebrow: 'Setting',
        title: 'Text that describes the setting, the neighborhood, and the materials of the place',
        text: 'Short text introducing Vieil Antibes, the terrace, the dining room, the bar, the stone, the wood, and the strongest visual elements of the restaurant.',
      },
      promise: {
        eyebrow: 'Promise',
        title: 'Text that sums up the restaurant promise and the expected experience',
        text: 'Short text explaining the cuisine, lunch-to-dinner rhythm, service style, and what guests should come here for.',
      },
      highlights: [
        'Short point about the terrace',
        'Short point about the bar',
        'Short point about the wood oven',
        'Short point about the materials',
      ],
    },
    contact: {
      eyebrow: 'Contact',
      title: 'Text that reassures people about booking, address, and practical information',
      text: 'Short text explaining how to book, how to get there, and where to find practical information quickly.',
      cards: [
        { title: 'Phone booking', value: 'Main phone number for reservations' },
        { title: 'WhatsApp', value: 'Direct message link or number' },
        { title: 'Email', value: 'Main restaurant email address' },
      ],
      addressTitle: 'Address',
      addressValue: 'Full restaurant address',
      hoursTitle: 'Hours',
      hourValue: 'Day schedule to be filled in',
      accessTitle: 'Access',
      accessText: 'Short text with useful landmarks, nearby parking if relevant, and the easiest way to reach the restaurant.',
    },
    legal: {
      eyebrow: 'Legal notice',
      title: 'Text that introduces the legal information to provide before launch',
      text: 'Short text indicating that the final legal information will replace these placeholders before the site goes live.',
      sections: [
        { title: 'Website publisher', body: 'Company name, legal form, address, company number, and legal representative.' },
        { title: 'Hosting', body: 'Hosting provider name, address, contact details, and useful technical information.' },
        { title: 'Personal data', body: 'Final legal text about data handling, contact form usage if any, and privacy policy.' },
      ],
    },
  },
  it: {
    menu: {
      eyebrow: 'Menu',
      title: 'Testo che introduce il menu e spiega che deve restare facile da aggiornare',
      text: 'Breve testo per presentare il menu, la logica delle categorie e il tono generale della cucina.',
      note: 'Istruzione cliente: sostituire ogni categoria, ogni piatto, ogni descrizione e ogni prezzo con i contenuti definitivi.',
      itemName: 'Nome del piatto',
      itemDescription: 'Breve descrizione del piatto, dei suoi ingredienti principali o del contorno.',
      itemPrice: 'Prezzo',
    },
    gallery: {
      eyebrow: 'Galleria',
      title: 'Testo che spiega quali tipi di foto fornire per mostrare il locale',
      text: 'Breve testo per indicare che questa pagina serve a mostrare la terrazza, la sala, il bar, il forno a legna, i piatti e i dettagli del ristorante.',
      captions: [
        'Foto ampia della terrazza',
        'Foto della sala principale',
        'Foto del forno a legna',
        'Foto di un piatto della casa',
        'Foto della tavola apparecchiata',
        'Foto del bar bistrot',
      ],
    },
    about: {
      eyebrow: 'Chi siamo',
      title: 'Testo che definisce l’identità del ristorante in poche righe',
      text: 'Breve testo per spiegare lo spirito del luogo, il quartiere, l’atmosfera e ciò che rende il ristorante diverso.',
      frame: {
        eyebrow: 'Il contesto',
        title: 'Testo che descrive il contesto, il quartiere e i materiali del luogo',
        text: 'Breve testo per presentare il Vieil Antibes, la terrazza, la sala, il bar, la pietra, il legno e gli elementi visivi forti del ristorante.',
      },
      promise: {
        eyebrow: 'La promessa',
        title: 'Testo che riassume la promessa del ristorante e l’esperienza attesa',
        text: 'Breve testo per spiegare il tipo di cucina, il ritmo pranzo e cena, lo stile di servizio e ciò che il cliente viene a cercare qui.',
      },
      highlights: [
        'Argomento breve sulla terrazza',
        'Argomento breve sul bar',
        'Argomento breve sul forno a legna',
        'Argomento breve sui materiali del luogo',
      ],
    },
    contact: {
      eyebrow: 'Contatti',
      title: 'Testo che rassicura sulla prenotazione, l’indirizzo e le informazioni pratiche',
      text: 'Breve testo per spiegare come prenotare, come arrivare e dove trovare rapidamente le informazioni utili.',
      cards: [
        { title: 'Prenotazione telefonica', value: 'Numero principale per le prenotazioni' },
        { title: 'WhatsApp', value: 'Link o numero per messaggio diretto' },
        { title: 'Email', value: 'Indirizzo email principale del ristorante' },
      ],
      addressTitle: 'Indirizzo',
      addressValue: 'Indirizzo completo del ristorante',
      hoursTitle: 'Orari',
      hourValue: 'Orari del giorno da indicare',
      accessTitle: 'Accesso',
      accessText: 'Breve testo con i punti di riferimento utili, il parcheggio se necessario e il modo più semplice per raggiungere il ristorante.',
    },
    legal: {
      eyebrow: 'Note legali',
      title: 'Testo che introduce le informazioni amministrative da fornire prima della messa online',
      text: 'Breve testo per indicare che le informazioni legali finali saranno sostituite prima della pubblicazione del sito.',
      sections: [
        { title: 'Editore del sito', body: 'Nome della società, forma giuridica, indirizzo, numero di registrazione e rappresentante legale.' },
        { title: 'Hosting', body: 'Nome dell’hosting provider, indirizzo, contatti e informazioni tecniche utili.' },
        { title: 'Dati personali', body: 'Testo legale finale sul trattamento dei dati, sull’eventuale modulo di contatto e sulla privacy policy.' },
      ],
    },
  },
  de: {
    menu: {
      eyebrow: 'Menü',
      title: 'Text, der die Karte einführt und erklärt, dass sie leicht zu pflegen bleiben soll',
      text: 'Kurzer Text, der das Menü, die Kategorienlogik und den allgemeinen Ton der Küche vorstellt.',
      note: 'Kundenhinweis: Jede Kategorie, jedes Gericht, jede Beschreibung und jeden Preis später durch die finalen Inhalte ersetzen.',
      itemName: 'Gerichtname',
      itemDescription: 'Kurze Beschreibung des Gerichts, seiner Hauptzutaten oder Beilage.',
      itemPrice: 'Preis',
    },
    gallery: {
      eyebrow: 'Galerie',
      title: 'Text, der erklärt, welche Fotoarten geliefert werden sollen, um den Ort zu zeigen',
      text: 'Kurzer Text, der erklärt, dass diese Seite Terrasse, Gastraum, Bar, Holzofen, Teller und Details des Restaurants zeigen soll.',
      captions: [
        'Breites Terrassenfoto',
        'Foto vom Hauptgastraum',
        'Foto vom Holzofen',
        'Foto vom Signature-Gericht',
        'Foto vom gedeckten Tisch',
        'Foto der Bistrobar',
      ],
    },
    about: {
      eyebrow: 'Über uns',
      title: 'Text, der die Identität des Restaurants in wenigen Zeilen festlegt',
      text: 'Kurzer Text, der den Geist des Ortes, das Viertel, die Atmosphäre und die Besonderheit des Restaurants erklärt.',
      frame: {
        eyebrow: 'Das Umfeld',
        title: 'Text, der den Rahmen, das Viertel und die Materialien des Ortes beschreibt',
        text: 'Kurzer Text über Vieil Antibes, Terrasse, Gastraum, Bar, Stein, Holz und die starken visuellen Elemente des Restaurants.',
      },
      promise: {
        eyebrow: 'Das Versprechen',
        title: 'Text, der das Restaurantversprechen und das erwartete Erlebnis zusammenfasst',
        text: 'Kurzer Text, der die Art der Küche, den Rhythmus von Mittag bis Abend, den Servicestil und den Grund für den Besuch erklärt.',
      },
      highlights: [
        'Kurzes Argument zur Terrasse',
        'Kurzes Argument zur Bar',
        'Kurzes Argument zum Holzofen',
        'Kurzes Argument zu den Materialien',
      ],
    },
    contact: {
      eyebrow: 'Kontakt',
      title: 'Text, der zu Reservierung, Adresse und praktischen Informationen beruhigt',
      text: 'Kurzer Text, der erklärt, wie man reserviert, wie man ankommt und wo die wichtigsten Informationen schnell zu finden sind.',
      cards: [
        { title: 'Telefonische Reservierung', value: 'Hauptnummer für Reservierungen' },
        { title: 'WhatsApp', value: 'Link oder Nummer für Direktnachricht' },
        { title: 'E-Mail', value: 'Haupt-E-Mail-Adresse des Restaurants' },
      ],
      addressTitle: 'Adresse',
      addressValue: 'Vollständige Adresse des Restaurants',
      hoursTitle: 'Öffnungszeiten',
      hourValue: 'Tageszeiten noch einzutragen',
      accessTitle: 'Anfahrt',
      accessText: 'Kurzer Text mit nützlichen Orientierungspunkten, Parkmöglichkeiten falls relevant und dem einfachsten Weg zum Restaurant.',
    },
    legal: {
      eyebrow: 'Impressum',
      title: 'Text, der die rechtlichen Informationen vor dem Launch einführt',
      text: 'Kurzer Text, der erklärt, dass die finalen rechtlichen Informationen diese Platzhalter vor dem Launch ersetzen werden.',
      sections: [
        { title: 'Seitenbetreiber', body: 'Name des Unternehmens, Rechtsform, Adresse, Registrierungsnummer und gesetzlicher Vertreter.' },
        { title: 'Hosting', body: 'Name des Hosting-Anbieters, Adresse, Kontaktdaten und nützliche technische Informationen.' },
        { title: 'Personenbezogene Daten', body: 'Finaler Rechtstext zu Datenverarbeitung, Kontaktformular falls vorhanden und Datenschutzerklärung.' },
      ],
    },
  },
  nl: {
    menu: {
      eyebrow: 'Menu',
      title: 'Tekst die het menu inleidt en uitlegt dat het eenvoudig moet blijven om te updaten',
      text: 'Korte tekst om het menu, de logica van de categorieën en de algemene toon van de keuken voor te stellen.',
      note: 'Klantinstructie: vervang later elke categorie, elk gerecht, elke beschrijving en elke prijs door de definitieve inhoud.',
      itemName: 'Naam van het gerecht',
      itemDescription: 'Korte beschrijving van het gerecht, de belangrijkste ingrediënten of het bijgerecht.',
      itemPrice: 'Prijs',
    },
    gallery: {
      eyebrow: 'Galerij',
      title: 'Tekst die uitlegt welke soorten foto’s moeten worden aangeleverd om de plek te tonen',
      text: 'Korte tekst die aangeeft dat deze pagina bedoeld is om het terras, de zaal, de bar, de houtoven, de gerechten en de details van het restaurant te tonen.',
      captions: [
        'Brede terrasfoto',
        'Foto van de hoofdzaal',
        'Foto van de houtoven',
        'Foto van een gerecht van het huis',
        'Foto van een gedekte tafel',
        'Foto van de bistrobar',
      ],
    },
    about: {
      eyebrow: 'Over ons',
      title: 'Tekst die de identiteit van het restaurant in enkele lijnen neerzet',
      text: 'Korte tekst die de geest van de plek, de buurt, de sfeer en wat het restaurant onderscheidt uitlegt.',
      frame: {
        eyebrow: 'Het kader',
        title: 'Tekst die het kader, de buurt en de materialen van de plek beschrijft',
        text: 'Korte tekst om Vieil Antibes, het terras, de zaal, de bar, steen, hout en de sterke visuele elementen van het restaurant voor te stellen.',
      },
      promise: {
        eyebrow: 'De belofte',
        title: 'Tekst die de belofte van het restaurant en de verwachte ervaring samenvat',
        text: 'Korte tekst om het type keuken, het ritme van middag en avond, de servicestijl en wat de gast hier komt zoeken uit te leggen.',
      },
      highlights: [
        'Kort argument over het terras',
        'Kort argument over de bar',
        'Kort argument over de houtoven',
        'Kort argument over de materialen',
      ],
    },
    contact: {
      eyebrow: 'Contact',
      title: 'Tekst die geruststelt over reserveren, adres en praktische informatie',
      text: 'Korte tekst die uitlegt hoe je reserveert, hoe je er geraakt en waar je snel de nuttige info vindt.',
      cards: [
        { title: 'Telefonische reservatie', value: 'Hoofdnummer voor reservaties' },
        { title: 'WhatsApp', value: 'Link of nummer voor direct bericht' },
        { title: 'E-mail', value: 'Hoofdmailadres van het restaurant' },
      ],
      addressTitle: 'Adres',
      addressValue: 'Volledig adres van het restaurant',
      hoursTitle: 'Openingstijden',
      hourValue: 'Daguren nog in te vullen',
      accessTitle: 'Bereikbaarheid',
      accessText: 'Korte tekst met nuttige herkenningspunten, parking indien nodig en de makkelijkste manier om het restaurant te bereiken.',
    },
    legal: {
      eyebrow: 'Juridische informatie',
      title: 'Tekst die de administratieve informatie inleidt die voor de lancering moet worden aangeleverd',
      text: 'Korte tekst die aangeeft dat de definitieve juridische informatie deze placeholders vóór publicatie zal vervangen.',
      sections: [
        { title: 'Uitgever van de site', body: 'Naam van de vennootschap, rechtsvorm, adres, ondernemingsnummer en wettelijke vertegenwoordiger.' },
        { title: 'Hosting', body: 'Naam van de hostingprovider, adres, contactgegevens en nuttige technische informatie.' },
        { title: 'Persoonsgegevens', body: 'Definitieve juridische tekst over gegevensverwerking, eventueel contactformulier en privacybeleid.' },
      ],
    },
  },
  es: {
    menu: {
      eyebrow: 'Menú',
      title: 'Texto que introduce la carta y explica que debe seguir siendo fácil de actualizar',
      text: 'Texto corto para presentar el menú, la lógica de las categorías y el tono general de la cocina.',
      note: 'Instrucción cliente: sustituir después cada categoría, plato, descripción y precio por los contenidos definitivos.',
      itemName: 'Nombre del plato',
      itemDescription: 'Breve descripción del plato, de sus ingredientes principales o de su acompañamiento.',
      itemPrice: 'Precio',
    },
    gallery: {
      eyebrow: 'Galería',
      title: 'Texto que explica qué tipos de fotos hay que proporcionar para mostrar el lugar',
      text: 'Texto corto para indicar que esta página sirve para mostrar la terraza, la sala, el bar, el horno de leña, los platos y los detalles del restaurante.',
      captions: [
        'Foto amplia de la terraza',
        'Foto de la sala principal',
        'Foto del horno de leña',
        'Foto de un plato de la casa',
        'Foto de la mesa puesta',
        'Foto del bar bistró',
      ],
    },
    about: {
      eyebrow: 'Sobre nosotros',
      title: 'Texto que define la identidad del restaurante en unas pocas líneas',
      text: 'Texto corto para explicar el espíritu del lugar, el barrio, el ambiente y lo que distingue al restaurante.',
      frame: {
        eyebrow: 'El marco',
        title: 'Texto que describe el entorno, el barrio y los materiales del lugar',
        text: 'Texto corto para presentar Vieil Antibes, la terraza, la sala, el bar, la piedra, la madera y los elementos visuales fuertes del restaurante.',
      },
      promise: {
        eyebrow: 'La promesa',
        title: 'Texto que resume la promesa del restaurante y la experiencia esperada',
        text: 'Texto corto para explicar el tipo de cocina, el ritmo de mediodía y noche, el estilo de servicio y lo que el cliente viene a buscar aquí.',
      },
      highlights: [
        'Argumento corto sobre la terraza',
        'Argumento corto sobre el bar',
        'Argumento corto sobre el horno de leña',
        'Argumento corto sobre los materiales del lugar',
      ],
    },
    contact: {
      eyebrow: 'Contacto',
      title: 'Texto que tranquiliza sobre la reserva, la dirección y la información práctica',
      text: 'Texto corto para explicar cómo reservar, cómo llegar y dónde encontrar rápidamente la información útil.',
      cards: [
        { title: 'Reserva telefónica', value: 'Número principal para las reservas' },
        { title: 'WhatsApp', value: 'Enlace o número para mensaje directo' },
        { title: 'Correo', value: 'Correo principal del restaurante' },
      ],
      addressTitle: 'Dirección',
      addressValue: 'Dirección completa del restaurante',
      hoursTitle: 'Horarios',
      hourValue: 'Horarios del día por completar',
      accessTitle: 'Acceso',
      accessText: 'Texto corto con puntos de referencia útiles, aparcamiento si hace falta y la mejor forma de llegar al restaurante.',
    },
    legal: {
      eyebrow: 'Aviso legal',
      title: 'Texto que introduce la información administrativa que debe proporcionarse antes de la publicación',
      text: 'Texto corto para indicar que la información legal final sustituirá estos placeholders antes de la publicación del sitio.',
      sections: [
        { title: 'Editor del sitio', body: 'Nombre de la sociedad, forma jurídica, dirección, número de registro y representante legal.' },
        { title: 'Hosting', body: 'Nombre del proveedor de hosting, dirección, contacto e información técnica útil.' },
        { title: 'Datos personales', body: 'Texto legal final sobre el tratamiento de datos, el formulario de contacto si lo hay y la política de privacidad.' },
      ],
    },
  },
  ru: {
    menu: {
      eyebrow: 'Меню',
      title: 'Текст, который вводит меню и объясняет, что его должно быть легко обновлять',
      text: 'Короткий текст, представляющий меню, логику категорий и общий тон кухни.',
      note: 'Инструкция для клиента: позже заменить каждую категорию, каждое блюдо, описание и цену на финальный контент.',
      itemName: 'Название блюда',
      itemDescription: 'Краткое описание блюда, его основных ингредиентов или гарнира.',
      itemPrice: 'Цена',
    },
    gallery: {
      eyebrow: 'Галерея',
      title: 'Текст, который объясняет, какие фото нужно предоставить, чтобы показать место',
      text: 'Короткий текст, объясняющий, что эта страница предназначена для показа террасы, зала, бара, дровяной печи, блюд и деталей ресторана.',
      captions: [
        'Широкое фото террасы',
        'Фото основного зала',
        'Фото дровяной печи',
        'Фото фирменного блюда',
        'Фото сервированного стола',
        'Фото барной стойки',
      ],
    },
    about: {
      eyebrow: 'О нас',
      title: 'Текст, который задаёт идентичность ресторана в нескольких строках',
      text: 'Короткий текст, который объясняет дух места, район, атмосферу и то, что отличает ресторан.',
      frame: {
        eyebrow: 'Обстановка',
        title: 'Текст, который описывает место, район и материалы интерьера',
        text: 'Короткий текст о Vieil Antibes, террасе, зале, баре, камне, дереве и сильных визуальных элементах ресторана.',
      },
      promise: {
        eyebrow: 'Обещание',
        title: 'Текст, который суммирует обещание ресторана и ожидаемый опыт',
        text: 'Короткий текст, объясняющий тип кухни, ритм дня и вечера, стиль сервиса и то, зачем сюда приходят гости.',
      },
      highlights: [
        'Короткий аргумент о террасе',
        'Короткий аргумент о баре',
        'Короткий аргумент о дровяной печи',
        'Короткий аргумент о материалах места',
      ],
    },
    contact: {
      eyebrow: 'Контакты',
      title: 'Текст, который успокаивает по поводу бронирования, адреса и практической информации',
      text: 'Короткий текст, который объясняет, как забронировать, как приехать и где быстро найти полезную информацию.',
      cards: [
        { title: 'Бронирование по телефону', value: 'Основной номер для бронирования' },
        { title: 'WhatsApp', value: 'Ссылка или номер для прямого сообщения' },
        { title: 'Почта', value: 'Основной адрес электронной почты ресторана' },
      ],
      addressTitle: 'Адрес',
      addressValue: 'Полный адрес ресторана',
      hoursTitle: 'Часы работы',
      hourValue: 'Часы работы на день нужно указать',
      accessTitle: 'Как добраться',
      accessText: 'Короткий текст с полезными ориентирами, парковкой при необходимости и самым простым способом добраться до ресторана.',
    },
    legal: {
      eyebrow: 'Правовая информация',
      title: 'Текст, который вводит юридическую информацию перед запуском',
      text: 'Короткий текст о том, что финальная юридическая информация заменит эти заглушки перед публикацией сайта.',
      sections: [
        { title: 'Издатель сайта', body: 'Название компании, юридическая форма, адрес, регистрационный номер и законный представитель.' },
        { title: 'Хостинг', body: 'Название хостинг-провайдера, адрес, контакты и полезная техническая информация.' },
        { title: 'Персональные данные', body: 'Финальный юридический текст о данных, контактной форме при наличии и политике конфиденциальности.' },
      ],
    },
  },
  uk: {
    menu: {
      eyebrow: 'Меню',
      title: 'Текст, що вводить меню та пояснює, що його має бути легко оновлювати',
      text: 'Короткий текст, який представляє меню, логіку категорій і загальний тон кухні.',
      note: 'Інструкція для клієнта: пізніше замінити кожну категорію, кожну страву, опис і ціну на фінальний контент.',
      itemName: 'Назва страви',
      itemDescription: 'Короткий опис страви, її основних інгредієнтів або гарніру.',
      itemPrice: 'Ціна',
    },
    gallery: {
      eyebrow: 'Галерея',
      title: 'Текст, що пояснює, які фото потрібно надати, щоб показати місце',
      text: 'Короткий текст, що пояснює, що ця сторінка призначена для показу тераси, зали, бару, дров’яної печі, страв і деталей ресторану.',
      captions: [
        'Широке фото тераси',
        'Фото головної зали',
        'Фото дров’яної печі',
        'Фото фірмової страви',
        'Фото сервірованого столу',
        'Фото барної стійки',
      ],
    },
    about: {
      eyebrow: 'Про нас',
      title: 'Текст, що задає ідентичність ресторану в кількох рядках',
      text: 'Короткий текст, який пояснює дух місця, район, атмосферу й те, що відрізняє ресторан.',
      frame: {
        eyebrow: 'Оточення',
        title: 'Текст, що описує контекст, район і матеріали простору',
        text: 'Короткий текст про Vieil Antibes, терасу, залу, бар, камінь, дерево та сильні візуальні елементи ресторану.',
      },
      promise: {
        eyebrow: 'Обіцянка',
        title: 'Текст, що підсумовує обіцянку ресторану та очікуваний досвід',
        text: 'Короткий текст, що пояснює тип кухні, ритм обіду й вечора, стиль сервісу та те, заради чого гість приходить сюди.',
      },
      highlights: [
        'Короткий аргумент про терасу',
        'Короткий аргумент про бар',
        'Короткий аргумент про дров’яну піч',
        'Короткий аргумент про матеріали місця',
      ],
    },
    contact: {
      eyebrow: 'Контакти',
      title: 'Текст, що заспокоює щодо бронювання, адреси та практичної інформації',
      text: 'Короткий текст, який пояснює, як забронювати, як дістатися і де швидко знайти корисну інформацію.',
      cards: [
        { title: 'Бронювання телефоном', value: 'Основний номер для бронювань' },
        { title: 'WhatsApp', value: 'Посилання або номер для прямого повідомлення' },
        { title: 'Пошта', value: 'Основна електронна адреса ресторану' },
      ],
      addressTitle: 'Адреса',
      addressValue: 'Повна адреса ресторану',
      hoursTitle: 'Години роботи',
      hourValue: 'Години на день потрібно вказати',
      accessTitle: 'Як дістатися',
      accessText: 'Короткий текст із корисними орієнтирами, паркуванням за потреби та найпростішим способом дістатися до ресторану.',
    },
    legal: {
      eyebrow: 'Юридична інформація',
      title: 'Текст, що вводить адміністративну інформацію перед запуском',
      text: 'Короткий текст про те, що фінальна юридична інформація замінить ці заглушки перед публікацією сайту.',
      sections: [
        { title: 'Видавець сайту', body: 'Назва компанії, юридична форма, адреса, реєстраційний номер і законний представник.' },
        { title: 'Хостинг', body: 'Назва хостинг-провайдера, адреса, контакти та корисна технічна інформація.' },
        { title: 'Персональні дані', body: 'Фінальний юридичний текст про дані, контактну форму за потреби та політику конфіденційності.' },
      ],
    },
  },
  zh: {
    menu: {
      eyebrow: '菜单',
      title: '介绍菜单并说明它应当便于更新的文本',
      text: '用于介绍菜单、分类逻辑以及整体菜品风格的简短文字。',
      note: '给客户的说明：之后将每个分类、每道菜、每段描述和每个价格替换为最终内容。',
      itemName: '菜名',
      itemDescription: '对菜品、主要食材或配菜的简短描述。',
      itemPrice: '价格',
    },
    gallery: {
      eyebrow: '图库',
      title: '说明应提供哪些类型照片来展示餐厅的文本',
      text: '简短说明此页面用于展示露台、餐厅大厅、吧台、木火炉、菜品以及餐厅细节。',
      captions: [
        '露台广角照片',
        '主餐厅照片',
        '木火炉照片',
        '招牌菜照片',
        '餐桌摆台照片',
        '法式吧台照片',
      ],
    },
    about: {
      eyebrow: '关于我们',
      title: '用几行文字建立餐厅身份感的文本',
      text: '简短说明餐厅的精神、所在街区、氛围，以及它与众不同之处。',
      frame: {
        eyebrow: '环境',
        title: '描述环境、街区与材质的文本',
        text: '简短介绍 Vieil Antibes、露台、餐厅大厅、吧台、石材、木材以及餐厅最强的视觉元素。',
      },
      promise: {
        eyebrow: '承诺',
        title: '概括餐厅承诺与预期体验的文本',
        text: '简短说明菜系类型、午晚节奏、服务风格，以及客人为什么会来到这里。',
      },
      highlights: [
        '关于露台的简短卖点',
        '关于吧台的简短卖点',
        '关于木火炉的简短卖点',
        '关于空间材质的简短卖点',
      ],
    },
    contact: {
      eyebrow: '联系',
      title: '让人放心预订、地址与实用信息的文本',
      text: '简短说明如何预订、如何前往，以及在哪里快速找到有用信息。',
      cards: [
        { title: '电话预订', value: '主要预订电话' },
        { title: 'WhatsApp', value: '直接消息链接或号码' },
        { title: '邮箱', value: '餐厅主要邮箱地址' },
      ],
      addressTitle: '地址',
      addressValue: '餐厅完整地址',
      hoursTitle: '营业时间',
      hourValue: '当天营业时间待填写',
      accessTitle: '到达方式',
      accessText: '简短说明有用地标、如有需要的停车信息，以及最容易抵达餐厅的方式。',
    },
    legal: {
      eyebrow: '法律信息',
      title: '上线前需要补充的法律信息介绍文本',
      text: '简短说明这些占位内容会在网站上线前由最终法律信息替换。',
      sections: [
        { title: '网站发布者', body: '公司名称、法律形式、地址、注册号和法定代表人。' },
        { title: '主机服务', body: '主机提供商名称、地址、联系方式和有用的技术信息。' },
        { title: '个人数据', body: '关于数据处理、如有联系表单以及隐私政策的最终法律文本。' },
      ],
    },
  },
  ja: {
    menu: {
      eyebrow: 'メニュー',
      title: 'メニューを紹介し、更新しやすい構成であることを伝えるテキスト',
      text: 'メニュー、カテゴリの考え方、料理全体のトーンを紹介する短い文章。',
      note: 'お客様向けメモ: 後で各カテゴリ、各料理、説明、価格を最終内容に置き換えてください。',
      itemName: '料理名',
      itemDescription: '料理、主な食材、または付け合わせを説明する短い文章。',
      itemPrice: '価格',
    },
    gallery: {
      eyebrow: 'ギャラリー',
      title: 'どんな写真を用意すべきかを説明するテキスト',
      text: 'このページでは、テラス、客席、バー、薪窯、料理、店内ディテールを見せることを想定しています。',
      captions: [
        'テラスの広角写真',
        'メインダイニングの写真',
        '薪窯の写真',
        '看板料理の写真',
        'テーブルセッティングの写真',
        'バーの写真',
      ],
    },
    about: {
      eyebrow: '店舗について',
      title: '数行でレストランの個性を伝えるテキスト',
      text: '店の雰囲気、立地、空気感、そして他と違うポイントを説明する短い文章。',
      frame: {
        eyebrow: '背景',
        title: '立地、周辺、素材感を伝えるテキスト',
        text: 'Vieil Antibes、テラス、ダイニング、バー、石、木材、そして店を象徴するビジュアル要素を紹介する短い文章。',
      },
      promise: {
        eyebrow: '約束',
        title: '店の約束と期待される体験をまとめるテキスト',
        text: '料理の方向性、昼と夜のリズム、サービスの雰囲気、そしてお客様がここに来る理由を説明する短い文章。',
      },
      highlights: [
        'テラスについての短い訴求',
        'バーについての短い訴求',
        '薪窯についての短い訴求',
        '空間素材についての短い訴求',
      ],
    },
    contact: {
      eyebrow: 'アクセス',
      title: '予約、住所、実用情報への安心感を与えるテキスト',
      text: '予約方法、行き方、役立つ情報をすばやく見つける方法を説明する短い文章。',
      cards: [
        { title: '電話予約', value: '予約用メイン電話番号' },
        { title: 'WhatsApp', value: '直接メッセージ用のリンクまたは番号' },
        { title: 'メール', value: 'レストランの主要メールアドレス' },
      ],
      addressTitle: '住所',
      addressValue: 'レストランの完全な住所',
      hoursTitle: '営業時間',
      hourValue: 'その日の営業時間を入力',
      accessTitle: '行き方',
      accessText: '目印、必要なら駐車場情報、そしてレストランへの最もわかりやすい行き方を説明する短い文章。',
    },
    legal: {
      eyebrow: '法的情報',
      title: '公開前に補う法的情報を案内するテキスト',
      text: 'これらの仮テキストは、サイト公開前に最終的な法的情報へ置き換えられることを説明する短い文章。',
      sections: [
        { title: 'サイト運営者', body: '会社名、法人形態、住所、登録番号、法定代表者。' },
        { title: 'ホスティング', body: 'ホスティング会社名、住所、連絡先、技術情報。' },
        { title: '個人情報', body: 'データ処理、必要に応じた問い合わせフォーム、プライバシーポリシーに関する最終法的文言。' },
      ],
    },
  },
};
